"""
export_corpus.py

Converts every task in one or more ARC-style datasets into a human-
readable .metta file: one file per task, containing an ASCII-art comment
for every grid followed by that grid's ground-fact atoms, in the
vocabulary defined by metta/representation.metta.

This is a derived-artifact generator, not a one-off script: rerun it
whenever the encoder changes, rather than hand-editing its output. The
generated corpus is intentionally NOT committed to git (see .gitignore);
it is regenerated from source datasets + this script, which are.

Usage:
    python python/export_corpus.py --dataset all
    python python/export_corpus.py --dataset conceptarc --out-dir exports/metta_corpus
    python python/export_corpus.py --dataset arc-agi --limit 5   # smoke test

Output layout:
    <out-dir>/<dataset>/<task_id>.metta      one file per task
    <out-dir>/manifest.md                    summary table (committed;
                                              small, useful for a status
                                              check without regenerating)
"""

from __future__ import annotations

import argparse
import glob
import json
import os
import sys
import time

sys.path.insert(0, os.path.dirname(__file__))

from encoder import GridEncoder, atoms_to_metta  # noqa: E402
from pretty import render_grid  # noqa: E402


DATASETS = {
    # name -> glob pattern for that dataset's task JSON files.
    # All three use the same plain {"train": [...], "test": [...]} layout,
    # so no per-dataset loader dispatch is needed.
    "arc-agi": "data/arc-agi/data/training/*.json",
    "conceptarc": "data/ConceptARC/corpus/*/*.json",
    "mini-arc": "data/mini-arc-real/data/MiniARC/*.json",
}


def load_task(fp: str) -> dict:
    with open(fp) as f:
        return json.load(f)


def task_id_for(fp: str, dataset: str) -> str:
    stem = os.path.splitext(os.path.basename(fp))[0]
    if dataset == "conceptarc":
        # ConceptARC file stems already include the concept group prefix
        # (e.g. "AboveBelow3"); keep as-is, it doubles as a group label.
        return stem
    return stem


CELL_LEVEL_PREDICATES = {"cell", "coord", "color", "adj"}


def export_task(fp: str, dataset: str, encoder: GridEncoder, out_path: str,
                 include_cells: bool = False) -> dict:
    """Encodes one task file to one .metta file. Returns stats dict.

    By default, cell-level atoms (cell/coord/color/adj) are omitted from
    the written file: they are >90% of atom volume, carry no information
    a human doesn't already get from the ASCII-art comment above each
    grid, and are not what blending operates on anyway (see
    metta/representation.metta's design-rule comment). Pass
    include_cells=True for the literal, complete ground-fact dump.

    Atoms are tagged with a dataset-qualified task id (`<dataset>__<tid>`)
    rather than the bare task id, so that loading multiple datasets'
    exported files into one shared MeTTa space (as Sprint C's cross-task
    candidate extraction will do) cannot silently conflate two tasks that
    happen to share a bare id across datasets. The file itself is still
    named by the bare id for readability, since directory nesting
    (<out-dir>/<dataset>/<tid>.metta) already disambiguates on disk.
    """
    task = load_task(fp)
    tid = task_id_for(fp, dataset)
    qualified_tid = f"{dataset}__{tid}"

    lines = [
        "; " + "=" * 74,
        f"; Task: {tid}  (dataset: {dataset}, qualified id: {qualified_tid})",
        "; Generated by python/export_corpus.py - GridEncoder defaults",
        f"; (background={encoder.background_rule}, "
        f"max_pairwise_objects={encoder.max_pairwise_objects}, "
        f"include_cells={include_cells})",
        "; " + "=" * 74,
        "",
    ]

    total_atoms = 0
    total_written = 0
    total_objects = 0
    capped_grids = 0
    n_grids = 0

    for split in ("train", "test"):
        for i, pair in enumerate(task.get(split, [])):
            for gname in ("input", "output"):
                if gname not in pair:
                    continue
                grid = pair[gname]
                label = f"{split}{i}_{gname}"
                atoms, objects = encoder.encode(qualified_tid, label, grid)

                if include_cells:
                    write_atoms = atoms
                else:
                    write_atoms = [a for a in atoms if a.predicate not in CELL_LEVEL_PREDICATES]

                lines.append(f"; --- {label} ({len(grid)}x{len(grid[0])}, "
                             f"{len(objects)} objects) ---")
                for row in render_grid(grid).split("\n"):
                    lines.append(f"; {row}")
                lines.append(atoms_to_metta(write_atoms))
                lines.append("")

                total_atoms += len(atoms)
                total_written += len(write_atoms)
                total_objects += len(objects)
                n_grids += 1
                if any(a.predicate == "tooManyObjects" for a in atoms):
                    capped_grids += 1

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as f:
        f.write("\n".join(lines))

    return {
        "task_id": tid,
        "n_grids": n_grids,
        "n_atoms": total_atoms,
        "n_written": total_written,
        "n_objects": total_objects,
        "capped_grids": capped_grids,
        "file_bytes": os.path.getsize(out_path),
    }


def export_dataset(dataset: str, out_dir: str, limit: int | None = None,
                    include_cells: bool = False) -> list:
    pattern = DATASETS[dataset]
    files = sorted(glob.glob(pattern))
    if limit:
        files = files[:limit]
    if not files:
        print(f"  [{dataset}] WARNING: no files matched {pattern} "
              f"(did you run `make data`?)")
        return []

    encoder = GridEncoder()
    stats = []
    t0 = time.time()
    for fp in files:
        tid = task_id_for(fp, dataset)
        out_path = os.path.join(out_dir, dataset, f"{tid}.metta")
        stats.append(export_task(fp, dataset, encoder, out_path, include_cells))
    dt = time.time() - t0

    total_atoms = sum(s["n_written"] for s in stats)
    total_bytes = sum(s["file_bytes"] for s in stats)
    print(f"  [{dataset}] {len(stats)} tasks, {sum(s['n_grids'] for s in stats)} grids, "
          f"{total_atoms} atoms written, {total_bytes/1e6:.1f} MB, {dt:.1f}s")
    return stats


def write_manifest(all_stats: dict, out_dir: str, include_cells: bool) -> None:
    lines = [
        "# MeTTa Corpus Export Manifest",
        "",
        "Auto-generated by `python/export_corpus.py`. Regenerate with "
        "`make export` rather than editing by hand.",
        "",
        f"Cell-level atoms (cell/coord/color/adj) {'INCLUDED' if include_cells else 'EXCLUDED'} "
        "in these files (see export_corpus.py docstring); the ASCII-art comment "
        "above each grid carries the same information for a human reader either way.",
        "",
        "`Capped grids` counts individual grids that hit the encoder's "
        "`max_pairwise_objects` cap, which is the same unit docs/decisions.md "
        "(D2, D4) reports; `Tasks affected` counts tasks containing at least "
        "one such grid. The two were previously conflated under one header.",
        "",
        "| Dataset | Tasks | Grids | Atoms written | Atoms total (incl. cells) | Objects | Capped grids | Tasks affected | Size (MB) |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for dataset, stats in all_stats.items():
        if not stats:
            continue
        lines.append(
            f"| {dataset} | {len(stats)} | {sum(s['n_grids'] for s in stats)} | "
            f"{sum(s['n_written'] for s in stats)} | "
            f"{sum(s['n_atoms'] for s in stats)} | "
            f"{sum(s['n_objects'] for s in stats)} | "
            f"{sum(s['capped_grids'] for s in stats)} | "
            f"{sum(1 for s in stats if s['capped_grids'] > 0)} | "
            f"{sum(s['file_bytes'] for s in stats)/1e6:.1f} |"
        )
    lines.append("")
    lines.append("Per-task breakdown available by regenerating with "
                  "`--limit` unset; not included here to keep this file small.")
    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, "manifest.md"), "w") as f:
        f.write("\n".join(lines))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dataset", choices=list(DATASETS) + ["all"], default="all")
    ap.add_argument("--out-dir", default="exports/metta_corpus")
    ap.add_argument("--limit", type=int, default=None,
                     help="Limit number of task files per dataset (for smoke tests)")
    ap.add_argument("--include-cells", action="store_true",
                     help="Include raw cell/coord/color/adj atoms in the "
                          "written files (off by default; see docstring)")
    args = ap.parse_args()

    datasets = list(DATASETS) if args.dataset == "all" else [args.dataset]
    print(f"Exporting to {args.out_dir}/ ...")
    all_stats = {}
    for d in datasets:
        all_stats[d] = export_dataset(d, args.out_dir, args.limit, args.include_cells)
    write_manifest(all_stats, args.out_dir, args.include_cells)
    print(f"Manifest written to {args.out_dir}/manifest.md")


if __name__ == "__main__":
    main()
